### PR TITLE
Update Foodcritic from 4.0.0 to 7.0.1

### PR DESCRIPTION
**Pull request by shortdudey123**

### CODE REVIEW

**Comment by shortdudey123** [comment]
Foodcritic >= 7.0 removed support for Ruby 2.0
Foodcritic >= 5.0 removed support for Ruby 1.9.3

Do we still need to support the EOL'd versions?  This would mean dropping support for Chef <12

**Comment by shortdudey123** [comment]
> Do we still need to support the EOL'd versions? This would mean dropping support for Chef <12

nevermind, saw your comment on https://github.com/mthssdrbrg/kafka-cookbook/issues/105
I will remove the version bump but still keep the FC rule fixes so they will not be an issue when the version is bumped

**Comment by mthssdrbrg** [comment]
Updated the Travis setup so `foodcritic` isn't run for Ruby 1.9.3 and merged the first commit of this PR in 492dff8e5190df6d2e62f12ca9ded3090acdf3a8. Thanks :)

**Comment by shortdudey123** [comment]
that works :)
Travis should probably still run foodcritic though (under ruby 2.1+) to verify that no violations appear.
Adding section to the travis matrix and only running foodcritic would probably suffice

**Comment by mthssdrbrg** [comment]
Yeah, Travis still runs foodcritic for the "[default](https://github.com/mthssdrbrg/kafka-cookbook/blob/master/.travis.yml#L2)" Ruby version (it's included in `bundle exec rake test`) :).

**Comment by shortdudey123** [comment]
Ah! missed that, cool :)

**Pull request closed without merging**
