### PR TITLE
Making the broker port non-mandatory for Kafka 0.9

### PR DESCRIPTION
**Pull request by aravindan-bk**
Hi,
  I just made this tiny change to the cookbook so that it can be used to install the bits for Kafka 0.9. If this change is merged to the original cookbook, please also make sure to mention in the Readme file that users using the updated cookbook should add the broker port in their wrapper cookbooks, if they want to install Kafka version < 0.9

### CODE REVIEW

**Comment by aravindan-bk** [comment]
Closing this because the failing tests weren't fixed

**Comment by mthssdrbrg** [comment]
I don't understand why this should be necessary for installing Kafka v0.9? Doesn't seem like they've removed the configuration option?

The main reason that the port is set to anything at all is that it's used in the init scripts, so to know when Kafka has started. Now that I think about it though, it should be possible to just check that the pid is still running X seconds after start (which is done when stopping Kafka), but I'm not entirely sure that this will work equally as well for the different init providers.

**Comment by aravindan-bk** [comment]
In 0.9 the configuration where "port " can be used in the config file has moved to something like this:

"listeners=PLAINTEXT://:6667"

More info on it here.
http://kafka.apache.org/documentation.html#brokerconfigs

In this case, it would be better if the user can choose to use the "port" option in their wrapper cookbooks for kafka < 0.9. For Kafka 0.9 and above, they can use the "listeners" option in their wrapper cookbooks. 

I understand that you use the port in kafka < 0.9 to test in your init scripts if the broker is started. 
May be doing something like "ps -ef | grep kafka" and then pulling the start-time would be an option for your test?

**Comment by mthssdrbrg** [comment]
@aravindan-bk: there's also another issue with `broker.id` sort of having become optional in `v0.9.0.0`. Currently thinking to make it possible to set both `broker.id` and `port` to `nil` when upgrading/running Kafka `v0.9.0.0` rather than having users set them explicitly when updating to `v0.9.0` (of this cookbook), as I think that would be a more natural approach (one should generally check what's changed with the configuration when upgrading Kafka...).

**Pull request closed without merging**
